### ISSUE TITLE
Tried netem ?

### ISSUE THREAD

**Issue by luqasz** [cnlohr/lamenet#1]
Hi.

You can achieve similar results with built in `netem` on linux. Have you tried it ? Just do a `man netem`. [This](https://wiki.linuxfoundation.org/networking/netem) may come in handy.

**Comment by cnlohr** [comment]
Yep, was originally going down that path but it was much more complicated to set up from what I remember, requiring IP tables, and/or kernel mods.  For this, you just give it two network interface devices and it handles the rest.
